services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    command: --bind_ip 0.0.0.0
    env_file:
      - .env
    volumes:
      - mongodbdata:/data/db
      - mongodbdata:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      default:
        ipv4_address: ${MONGO_IP}

  webui:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    container_name: webui
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=webui
    volumes:
      - ../../open5gs/webui:/mnt/webui
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9999/tcp"
    ports:
      - "9999:9999/tcp"
    networks:
      default:
        ipv4_address: ${WEBUI_IP}

  nrf:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    container_name: nrf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=nrf
    volumes:
      - ../../5g/nrf:/mnt/nrf
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${NRF_IP}

  scp:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
    container_name: scp
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=scp
    volumes:
      - ../../5g/scp:/mnt/scp
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${SCP_IP}

  ausf:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
      - scp
    container_name: ausf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ausf
    volumes:
      - ../../5g/ausf:/mnt/ausf
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${AUSF_IP}

  udr:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: udr
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=udr
    volumes:
      - ../../5g/udr:/mnt/udr
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${UDR_IP}

  udm:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
      - scp
    container_name: udm
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=udm
    volumes:
      - ../../5g/udm:/mnt/udm
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${UDM_IP}

  pcf:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: pcf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcf
    volumes:
      - ../../5g/pcf:/mnt/pcf
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
      - "9091/tcp"
    networks:
      default:
        ipv4_address: ${PCF_IP}

  bsf:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
      - scp
      - mongo
    container_name: bsf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=bsf
    volumes:
      - ../../5g/bsf:/mnt/bsf
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: ${BSF_IP}

  smf:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
      - scp
      - amf
    container_name: smf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=smf
      - DEPLOY_MODE=5G
    volumes:
      - ../../5g/smf:/mnt/smf
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/tcp"
      - "3868/sctp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
      - "9091/tcp"
    networks:
      default:
        ipv4_address: ${SMF_IP}

  upf:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
      - scp
      - smf
    container_name: upf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=upf
    volumes:
      - ../../5g/upf:/mnt/upf
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2152/udp"
      - "8805/udp"
      - "9091/tcp"
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      default:
        ipv4_address: ${UPF_IP}

  amf:
    build:
      context: ../..
      dockerfile: open5gs/base/Dockerfile
    depends_on:
      - nrf
      - scp
      - ausf
      - udm
      - udr
      - pcf
      - bsf
    container_name: amf
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=amf
    volumes:
      - ../../5g/amf:/mnt/amf
      - ../../log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "38412/sctp"
      - "7777/tcp"
      - "9091/tcp"
    networks:
      default:
        ipv4_address: ${AMF_IP}

# ---- RAN ----
  srsgnb_zmq:
    build:
      context: ../..
      dockerfile: ran/srsran/Dockerfile
    depends_on:
      - amf
    container_name: srsgnb_zmq
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ../../ran/srsran:/mnt/srsran
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=gnb_zmq
      - STARTUP_DELAY=60  # AMF(5GC)起動を待つ
    expose:
      - "38412/sctp"
      - "2152/udp"
      - "2000/tcp"
      - "2001/tcp"
    networks:
      default:
        ipv4_address: ${SRS_GNB_IP}

  srsue_5g_zmq:
    build:
      context: ../..
      dockerfile: ran/srslte/Dockerfile
    container_name: srsue_5g_zmq
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ../../ran/srslte:/mnt/srslte
      - ../../ran/srsue:/mnt/srsue
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ue_5g_zmq
      - STARTUP_DELAY=75  # gNB起動を待つ
    expose:
      - "2000/tcp"
      - "2001/tcp"
    networks:
      default:
        ipv4_address: ${SRS_UE_IP}

networks:
  default:
    external: true
    name: br-open5gs_5g

volumes:
  mongodbdata:
    name: docker_open5gs_mongodbdata
    external: true
